name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Installing dependencies
      run: sudo apt install npm
    - name: Installing grunt-cli
      run: npm install -g grunt-cli
    - name: Building package
      run: |
        npm install
        grunt
